### ISSUE TITLE
Подготовить дизайн QML

### ISSUE THREAD

**Issue by EndrII** [QuasarApp/SoundBand#17]
Подготовить дизайн QML (мобилки + десктоп)

**Comment by EndrII** [comment]
разработка qml приложения в данном [пр](https://github.com/QuasarApp/AlcoParty/pull/43)

**Comment by EndrII** [comment]
первая qml обертка готова, можно по ней делать дизайн.

**Comment by EndrII** [comment]
![главный экран](https://user-images.githubusercontent.com/12465465/35099323-9fbac5aa-fc68-11e7-844e-ffc9bf956951.png)
![экран со списком доступных плей листов  ](https://user-images.githubusercontent.com/12465465/35099356-bede7cc4-fc68-11e7-86fd-42c84587b8ab.png)

**Comment by EndrII** [comment]
с начало стоит реализовать логику, так как тут нечего нет

**Comment by EndrII** [comment]
есть новости по дизайну ?

**Comment by EndrII** [comment]
состояния плейбека :

Constant | Value | Description
-- | -- | --
QMediaPlaylist::CurrentItemOnce | 0 | The current item is played only once.
QMediaPlaylist::CurrentItemInLoop | 1 | The current item is played repeatedly in a loop.
QMediaPlaylist::Sequential | 2 | Playback  starts from the current and moves through each successive item until  the last is reached and then stops. The next item is a null item when  the last one is currently playing.
QMediaPlaylist::Loop | 3 | Playback restarts at the first item after the last has finished playing.
QMediaPlaylist::Random | 4 | Play items in random order.

**Comment by zig1hai** [comment]
![designereference](https://user-images.githubusercontent.com/29816673/38817255-a560bdfc-41a0-11e8-8565-d1486f266325.png)
![iconsreference](https://user-images.githubusercontent.com/29816673/38817267-ac75cfce-41a0-11e8-9897-b4fd99d53814.png)
[Icons.zip](https://github.com/QuasarApp/SoundBand/files/1915907/Icons.zip)
