### ISSUE TITLE
Написать класс логирования

### ISSUE THREAD

**Issue by EndrII** [QuasarApp/SoundBand#44]
класс должен иметь статичный метотод который будет писать сообщения в файл (*.log)
запись в файле должна иметь следующий вид:
`(время сообщения) (место где произошло файл + номер строки, ( это опционально если получиться)): сообщение.`

**Comment by EndrII** [comment]
http://doc.qt.io/qt-5/qfile.html
http://cppstudio.com/post/446/
http://doc.qt.io/qt-5/qtime.html

**Comment by usermeme** [comment]
Класс Log был создан
