### ISSUE TITLE
Please upload an AppImage to GitHub Releases

### ISSUE THREAD

**Issue by probonopd** [QuasarApp/SoundBand#74]
https://github.com/QuasarApp/SoundBand/blob/cb003386050a82717e315b0ce8d98f0866afc92b/installer/deploy/deploy.pro#L16

Please upload a SoundBand AppImage to GitHub Releases, thank you.

**Comment by probonopd** [comment]
Great. Please let me know if you are running into any issues.

**Comment by EndrII** [comment]
Okay.
Thank you

**Comment by EndrII** [comment]
this project is close
